### ISSUE TITLE
手动设置码率无效

### ISSUE THREAD

**Issue by WorldlineChanger** [pjlt/lanthing-pc#184]
串流过程中手动设置码率无效，如设置为2Mbps后，画面变动剧烈时速率仍然可达到10Mbps以上
希望可以记住码率设置

**Comment by numbaa** [comment]
请问你的被控是什么显卡？

**Comment by WorldlineChanger** [comment]
抱歉，主控J4125（UHD600），被控3070ti

**Comment by numbaa** [comment]
原先在被控端是英伟达显卡的情况下确实有码率不准的问题，最新的v0.3.2已经修复该问题，画质也随着这个bug的修复得到比较可观的改善。

当前的逻辑是：当设置`X Mbps`码率，允许波峰达到`X Mbps * 1.15`。但观测下来，在画面剧烈变化时仍然会有短时间超过这个最大值（也有可能是测速软件不准），这个问题无法通过外部代码解决，是英伟达显卡内部的问题。

关闭该issue。
