### ISSUE TITLE
部分组合快捷键无法输入被控端

### ISSUE THREAD

**Issue by WorldlineChanger** [pjlt/lanthing-pc#185]
使用alt+tab时，会导致主控端触发，被控端无法正确接收。
个人建议与qd类似，主控窗口失焦后再接收快捷键输入，聚焦时将快捷键传入被控

**Comment by numbaa** [comment]
已确认

**Comment by numbaa** [comment]
在 #187 修复，已打包在v0.2.3，观察一段时间。

**Comment by WorldlineChanger** [comment]
感谢回复，测试alt+tab没问题了。但还有部分快捷键（如 Snipaste 的 F1 键）和 F3 键似乎无法传入，测试如图
![snipaste_20240116_171144](https://github.com/pjlt/lanthing-pc/assets/46261730/a413c81e-e873-471a-8705-e3c174d756f6)

**Comment by WorldlineChanger** [comment]
> 感谢回复，测试alt+tab没问题了。但还有部分快捷键（如 Snipaste 的 F1 键）和 F3 键似乎无法传入，测试如图

经测试关闭主控端Snipaste后恢复正常，可能是优先级原因，不过qd没有这个问题，不知优化难度如何

**Comment by numbaa** [comment]
lanthing捕获输入和qd用的是不同的技术，这个问题通过打补丁的方式不一定好做。我先研究一下好不好做，不好做就先放一放，以后有时间再大改。

**Comment by WorldlineChanger** [comment]
理解，老大辛苦了
