### ISSUE TITLE
能否加一个设置项

### ISSUE THREAD

**Issue by 1789984734** [pjlt/lanthing-pc#210]
你好，能否在设置页面加一个设置，让用户可以选择点击关闭按钮时是执行最小化到任务栏还是直接退出程序，谢谢。

**Comment by numbaa** [comment]
最开始设计的时候考虑过这种交互，后面还是做成现在这个样子：
1. 点`—`是最小化到任务栏
2. 点`X`是最小化到托盘
3. 对托盘图标`右键`-`退出`退出程序

保持一个交互对应一个功能，这种不太影响体验的东西，不打算做成可配置的。

**Comment by 1789984734** [comment]
好吧，感谢回复
